'use strict';

const fs = require('fs');
const path = require('path');

const SPEC_OUTPUT_DIR = path.resolve(__dirname, '../../tests/generated');

class PlaywrightRunner {
  generateSpec(testCasesPath) {
    const raw = fs.readFileSync(testCasesPath, 'utf-8');
    const data = JSON.parse(raw);

    const { meta, test_cases } = data;
    const baseUrl = meta.input.startsWith('http') ? meta.input : process.env.BASE_URL || 'https://example.com';

    const specContent = this._buildSpecFile(test_cases, baseUrl, meta);

    const specFilename = path.basename(testCasesPath).replace('test-cases-', 'generated-').replace('.json', '.spec.js');
    const specPath = path.join(SPEC_OUTPUT_DIR, specFilename);

    fs.writeFileSync(specPath, specContent);
    console.log(`✓ Playwright spec → ${specPath}`);

    return specPath;
  }

  _buildSpecFile(testCases, baseUrl, meta) {
    const tests = testCases.map((tc) => this._buildTest(tc, baseUrl)).join('\n\n');

    return `// Auto-generated by AI Test Case Generator
// Input: ${meta.input}
// Generated: ${meta.generatedAt}
// Do not edit manually — regenerate with: npm run generate

const { test, expect } = require('@playwright/test');

test.describe('Generated Test Suite', () => {
  test.describe.configure({ mode: 'parallel' });

${tests}
});
`;
  }

  _buildTest(tc, baseUrl) {
    const steps = tc.steps.map((step) => this._convertStep(step, baseUrl)).join('\n    ');
    const safeTitle = tc.title.replace(/'/g, "\\'");

    return `  test('${safeTitle}', async ({ page }) => {
    // Expected: ${tc.expected}
    ${steps}
  });`;
  }

  _convertStep(step, baseUrl) {
    const s = step.toLowerCase();

    if (s.includes('navigate to') || s.includes('ir a') || s.includes('go to')) {
      const urlMatch = step.match(/https?:\/\/[^\s]+/);
      const target = urlMatch ? urlMatch[0] : baseUrl;
      return `await page.goto('${target}');`;
    }

    if (s.includes('wait for') || s.includes('esperar')) {
      return `await page.waitForLoadState('domcontentloaded');`;
    }

    if (s.includes('viewport') || s.includes('mobile') || s.includes('375')) {
      return `await page.setViewportSize({ width: 375, height: 667 });`;
    }

    if (s.includes('click') || s.includes('pulsar') || s.includes('press tab')) {
      if (s.includes('tab')) return `await page.keyboard.press('Tab');`;
      const el = this._extractElement(step);
      return `await page.locator('${el}').first().click();`;
    }

    if (s.includes('fill') || s.includes('type') || s.includes('introducir') || s.includes('enter')) {
      const el = this._extractElement(step);
      return `await page.locator('${el}').first().fill('test-value');`;
    }

    if (s.includes('verify') || s.includes('check') || s.includes('assert') || s.includes('verif')) {
      if (s.includes('title') || s.includes('título')) {
        return `expect(await page.title()).not.toBe('');`;
      }
      if (s.includes('url') || s.includes('redirect')) {
        return `expect(page.url()).not.toBe('about:blank');`;
      }
      if (s.includes('visible') || s.includes('display')) {
        return `await expect(page.locator('body')).toBeVisible();`;
      }
      if (s.includes('overflow') || s.includes('horizontal')) {
        return `const overflow = await page.evaluate(() => document.body.scrollWidth > window.innerWidth);\n    expect(overflow).toBe(false);`;
      }
      if (s.includes('focus') || s.includes('keyboard')) {
        return `await expect(page.locator(':focus').first()).toBeVisible();`;
      }
      return `await expect(page.locator('body')).toBeVisible();`;
    }

    if (s.includes('tab') || s.includes('navigate') || s.includes('identify')) {
      return `// Step: ${step}\n    await page.waitForLoadState('networkidle');`;
    }

    return `// Step: ${step}\n    await page.waitForTimeout(500);`;
  }

  _extractElement(step) {
    const lower = step.toLowerCase();
    if (lower.includes('heading') || lower.includes('h1') || lower.includes('título')) return 'h1';
    if (lower.includes('button') || lower.includes('botón') || lower.includes('login') || lower.includes('submit')) return '[type="submit"], button';
    if (lower.includes('link') || lower.includes('enlace') || lower.includes('navigation')) return 'nav a';
    if (lower.includes('input') || lower.includes('field') || lower.includes('usuario')) return 'input[type="text"]';
    if (lower.includes('password') || lower.includes('contraseña')) return 'input[type="password"]';
    if (lower.includes('email')) return 'input[type="email"]';
    return 'body';
  }
}

module.exports = PlaywrightRunner;
